output_dir: out
metapackage: metapackage.smpkg
new_metapackage: new_metapackage.smpkg
gtdb_protein_faa_reps: protein_faa_reps
gtdb_bac_tax: bac120_taxonomy_r207.tsv
gtdb_arc_tax: ar53_taxonomy_r207.tsv
pfams: HMMs/Pfam
tigrfams: HMMs/TIGRfams.HMM
uniprot_seq: uniprot_sprot.fa
uniprot_tax: uniprot_sprot_taxonomy.tsv
sra_seqs_1:
  SRR1234: SRR1234_1.fastq
sra_seqs_2:
  SRR1234: SRR1234_2.fastq
