output_dir: /work/microbiome/msingle/sam/1_gtdb_r207_smpkg/20220513
metapackage: /work/microbiome/msingle/mess/89_S3.metapackage_20211101.smpkg
new_metapackage: S3.metapackage_20220513.smpkg
gtdb_protein_faa_reps: /scratch/microbiome/aroneys/projects/12-SingleM-gtdb-r207/data/processed/protein_faa_reps
gtdb_bac_tax: /work/microbiome/db/gtdb/gtdb_release207/bac120_taxonomy_r207.tsv
gtdb_arc_tax: /work/microbiome/db/gtdb/gtdb_release207/ar53_taxonomy_r207.tsv
pfams: /work/microbiome/msingle/sam/HMMs/Pfam
tigrfams: /work/microbiome/msingle/sam/HMMs/TIGRfams.HMM
uniprot_seq: /work/microbiome/abisko/aroneys/uniprot/uniref100_20210616/uniprot_sprot.fa
uniprot_tax: /work/microbiome/abisko/aroneys/uniprot/uniref100_20210616/uniprot_sprot_taxonomy.tsv
