output_dir: ~/m/msingle/mess/97_gtdb_r207_smpkg/20220513
metapackage: ~/m/msingle/mess/89_S3.metapackage_20211101.smpkg
new_metapackage: S3.metapackage_20220513.smpkg
gtdb_protein_faa_reps: ~/s/aroneys/projects/12-SingleM-gtdb-r207/data/processed/protein_faa_reps
gtdb_bac_tax: ~/m/db/gtdb/gtdb_release207/bac120_taxonomy_r207.tsv
gtdb_arc_tax: ~/m/db/gtdb/gtdb_release207/ar53_taxonomy_r207.tsv
pfams: ~/m/msingle/mess/97_gtdb_r207_smpkg/HMMs/Pfam
tigrfams: ~/m/msingle/mess/97_gtdb_r207_smpkg/HMMs/TIGRfams.HMM
uniprot_seq: ~/m/abisko/aroneys/uniprot/uniref100_20210616/uniprot_sprot.fa
uniprot_tax: ~/m/abisko/aroneys/uniprot/uniref100_20210616/uniprot_sprot_taxonomy.tsv
